name: Release and Publish

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: lalexdotcom/action-release-and-publish@v1
        with:
          publish: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}